[tool.poetry]
name = "pydeck-shared"
version = "0.1.0"
description = ""
authors = ["virashu <virashu@disroot.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
